text = "samuel parker"
print("Original: ",text)
print("Strip: ",text.strip())
print("Upper: ",text.upper())
print("Lower: ",text.lower())
print("Swapcase: ",text.swapcase())
print("Title: ",text.title())
print("Capitalize: ",text.capitalize())
print("Replace:",text.replace("parker","spartan"))
print("Count: ",text.count("m"))
print("Index of s:",text.index("s"))
print("Index of r:",text.index("r"))
print("Text: ",text.count("a"))
print("Text: ",text.find("p"))
print("Text: ",text.find("f"))
print("Last character: ",text[-1])
print("Second last: ",text[-2])
print("Text: ",text[4])
print("Text: ",text[4:9])
print("Text: ",text[4:])
print("Text: ",text[:13])
print("Split: ",text.split(" "))